In [8]:
import torch 

In [2]:
x = torch.tensor(1, requires_grad=True)
w = torch.tensor(2, requires_grad=True)
b = torch.tensor(3, requires_grad=True)

In [6]:
# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2)
tensor(1)
tensor(1)


In [9]:
x = torch.ones(1) * 4

In [10]:
y = torch.ones(1) * 2

In [11]:
x + y

tensor([ 6.])

In [12]:
x

tensor([ 4.])

In [13]:
y

tensor([ 2.])

In [22]:
import torch.nn
from torch.autograd import Variable

x = Variable(torch.ones([2, 2]) * 2)

In [23]:
while x.sum() < 100:
    x = torch.nn.ReLU()(x**2)
    print(x)

tensor([[ 4.,  4.],
        [ 4.,  4.]])
tensor([[ 16.,  16.],
        [ 16.,  16.]])
tensor([[ 256.,  256.],
        [ 256.,  256.]])


In [45]:
x = Variable(torch.ones(1) * 2, requires_grad=True)
x

tensor([ 2.])

In [46]:
z = 2 * (x * x) + 5 * x
z


tensor([ 18.])

In [47]:
r = z.backward(torch.ones(1) * 5)

In [48]:
print(x.grad)

tensor([ 65.])


In [49]:
13 * 5

65

In [62]:
rt = Variable(torch.ones(1), requires_grad=True)

In [63]:
f = rt * rt + 1

In [64]:
f.backward()


In [65]:
rt.grad

tensor([ 2.])